version: '3'
services:
  postgreSQL:
    image: postgres:13.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=empik
      - POSTGRES_USER=empik
      - POSTGRES_DB=empik
      - PGDATA=/var/run/postgresql
    volumes:
      - postgresql_data:/var/lib/postgresql/data/pgdata

volumes:
  postgresql_data:
